# Generated by Django 5.2.7 on 2025-10-05 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='ชื่อกิจกรรม', max_length=200)),
                ('description', models.TextField(help_text='รายละเอียดกิจกรรม')),
                ('start_datetime', models.DateTimeField(help_text='วันและเวลาที่เริ่มกิจกรรม')),
                ('location', models.CharField(help_text='สถานที่จัดกิจกรรม', max_length=200)),
                ('max_participants', models.PositiveIntegerField(default=100, help_text='จำนวนผู้เข้าร่วมสูงสุด')),
                ('category', models.CharField(choices=[('general', 'ทั่วไป'), ('workshop', 'เวิร์กช็อป'), ('conference', 'สัมมนา'), ('meetup', 'มีตติ้ง / Networking'), ('online', 'ออนไลน์')], default='general', help_text='ประเภทของกิจกรรม', max_length=50)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Confirmed', 'ยืนยันแล้ว'), ('Pending', 'รอดำเนินการ'), ('Cancelled', 'ยกเลิก')], default='Confirmed', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
