# Generated by Django 5.2.7 on 2025-10-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_female',
            field=models.BooleanField(default=True, help_text='อนุญาตให้ผู้หญิงเข้าร่วม'),
        ),
        migrations.AddField(
            model_name='event',
            name='allow_male',
            field=models.BooleanField(default=True, help_text='อนุญาตให้ผู้ชายเข้าร่วม'),
        ),
    ]
